# path.data: /var/lib/logstash
# path.config: /etc/logstash/conf.d
http.host: "0.0.0.0"
# http.port: 5046
path.logs: /var/log/logstash

# xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]